class CfgPatches
{
    class EoH_DeltaForceDurability
    {
        units[] = {};
        weapons[] = {};
        requiredVersion = 0.1;
        requiredAddons[] =
        {
            "DZ_Data",
            "DZ_Characters",
            "DZ_Characters_Backpacks",
            "DZ_Characters_Headgear",
            "DZ_Characters_Glasses",
            "DZ_Characters_Vests",
            "DZ_Sounds_Effects",
            "My_DF_Gear_Scripts"
        };
    };
};

class CfgVehicles
{
    // Backpacks
    class My_DF_Gear_Backpacks_Shiled2;
    class My_DF_Gear_Backpacks_Large_Mountain;
    class My_DF_Gear_Backpacks_Camping;
    class My_DF_Gear_Backpacks_Cross;
    class My_DF_Gear_Backpacks_D2;
    class My_DF_Gear_Backpacks_D3;
    class My_DF_Gear_Backpacks_D7;
    class My_DF_Gear_Backpacks_DASH;
    class My_DF_Gear_Backpacks_DG;
    class My_DF_Gear_Backpacks_Doctor;
    class My_DF_Gear_Backpacks_Engineering_Shield_LV1;
    class My_DF_Gear_Backpacks_Engineering_Shield_LV2;
    class My_DF_Gear_Backpacks_Engineering_Shield_LV3;
    class My_DF_Gear_Backpacks_Engineering_Shield_LV4;
    class My_DF_Gear_Backpacks_Field_hiking;
    class My_DF_Gear_Backpacks_GA;
    class My_DF_Gear_Backpacks_GT1;
    class My_DF_Gear_Backpacks_GT5;
    class My_DF_Gear_Backpacks_GTO;
    class My_DF_Gear_Backpacks_Heavy_Mountain;
    class My_DF_Gear_Backpacks_HLS2;
    class My_DF_Gear_Backpacks_Kai;
    class My_DF_Gear_Backpacks_Kai_Haavk;
    class My_DF_Gear_Backpacks_King;
    class My_DF_Gear_Backpacks_Zoya_Angel;
    class My_DF_Gear_Backpacks_Large_sports;
    class My_DF_Gear_Backpacks_Lightweight_Outdoor;
    class My_DF_Gear_Backpacks_Lightweight_Outdoor2;
    class My_DF_Gear_Backpacks_MAP;
    class My_DF_Gear_Backpacks_Raid_Tactical;
    class My_DF_Gear_Backpacks_Rainforest_hunter;
    class My_DF_Gear_Backpacks_Rocket;
    class My_DF_Gear_Backpacks_Roy;
    class My_DF_Gear_Backpacks_Roy_Haavk;
    class My_DF_Gear_Backpacks_Roy_mourners;
    class My_DF_Gear_Backpacks_Rucksack;
    class My_DF_Gear_Backpacks_SergeantWilson;
    class My_DF_Gear_Backpacks_Shiled;
    class My_DF_Gear_Backpacks_Sineva_Tincan;
    class My_DF_Gear_Backpacks_Sports;
    class My_DF_Gear_Backpacks_Subrosa;
    class My_DF_Gear_Backpacks_Tactical;
    class My_DF_Gear_Backpacks_Terry;
    class My_DF_Gear_Backpacks_Terry_Haavk;
    class My_DF_Gear_Backpacks_Travel;

    // Headgear / masks / NVG / visor pieces
    class My_DF_Gear_Heads_GT5;
    class My_DF_Gear_Heads_Benny;
    class My_DF_Gear_Heads_Butterfly;
    class My_DF_Gear_Heads_D6;
    class My_DF_Gear_Heads_D6_Visor;
    class My_DF_Gear_Heads_DAS;
    class My_DF_Gear_Heads_David_Savage;
    class My_DF_Gear_Heads_DICH;
    class My_DF_Gear_Heads_DICH1;
    class My_DF_Gear_Heads_DICH9;
    class My_DF_Gear_Heads_Dragon;
    class My_DF_Gear_Heads_Dragon_NVG;
    class My_DF_Gear_Heads_Dragon_Outers;
    class My_DF_Gear_Heads_Dragon_Outers_NVG;
    class My_DF_Gear_Heads_DRO;
    class My_DF_Gear_Heads_Elio;
    class My_DF_Gear_Heads_Elio_NVG;
    class My_DF_Gear_Heads_Eversmann;
    class My_DF_Gear_Heads_Flamethrower;
    class My_DF_Gear_Heads_Flamethrower_Visor;
    class My_DF_Gear_Heads_FPilot;
    class My_DF_Gear_Heads_GN;
    class My_DF_Gear_Heads_GN_Heavy;
    class My_DF_Gear_Heads_GN_Heavy_NVG;
    class My_DF_Gear_Heads_GT1;
    class My_DF_Gear_Heads_Guard;
    class My_DF_Gear_Heads_Guard_NVG;
    class My_DF_Gear_Heads_H01;
    class My_DF_Gear_Heads_H07;
    class My_DF_Gear_Heads_H09;
    class My_DF_Gear_Heads_H09_Visor;
    class My_DF_Gear_Heads_H70;
    class My_DF_Gear_Heads_H70_NVG;
    class My_DF_Gear_Hat_Reis;
    class My_DF_Gear_Heads_Headphone;
    class My_DF_Gear_Heads_Headphone2;
    class My_DF_Gear_Heads_Headphone3;
    class My_DF_Gear_Heads_Heavy_Armor;
    class My_DF_Gear_Heads_Heavy_Armor_Visor;
    class My_DF_Gear_Heads_Heavy_Armor2;
    class My_DF_Gear_Heads_Heavy_Armor2_Visor;
    class My_DF_Gear_Heads_Heavy;
    class My_DF_Gear_Heads_Heavy_Visor;
    class My_DF_Gear_Heads_Hoot;
    class My_DF_Gear_Heads_Kai;
    class My_DF_Gear_Heads_Long;
    class My_DF_Gear_Heads_Long_NVG;
    class My_DF_Gear_Heads_Luna_Black;
    class My_DF_Gear_Heads_Luna_Olymp;
    class My_DF_Gear_Heads_Mask;
    class My_DF_Gear_Heads_Mask_Visor;
    class My_DF_Gear_Heads_MC;
    class My_DF_Gear_Heads_MC201;
    class My_DF_Gear_Heads_MHS;
    class My_DF_Gear_Heads_Mythic;
    class My_DF_Gear_Heads_Mythic_NVG;
    class My_DF_Gear_Heads_Nightsuit;
    class My_DF_Gear_Heads_Nightsuit_NVG;
    class My_DF_Gear_Heads_Old;
    class My_DF_Gear_Heads_OperationDragon;
    class My_DF_Gear_Heads_Outdoor;
    class My_DF_Gear_Heads_Pilot;
    class My_DF_Gear_Heads_Riot;
    class My_DF_Gear_Heads_Safety;
    class My_DF_Gear_Heads_Said;
    class My_DF_Gear_Heads_Scout;
    class My_DF_Gear_Heads_SergeantWilson;
    class My_DF_Gear_Heads_SergeantWilson_NVG;
    class My_DF_Gear_Heads_Sineva;
    class My_DF_Gear_Heads_Sineva_Visor;
    class My_DF_Gear_Heads_Sineva_Tincan;
    class My_DF_Gear_Heads_Sineva_Tincan_Visor;
    class My_DF_Gear_Heads_Vintage;

    // Rigs / vests / powered rig variants
    class My_DF_Gear_Rigs_Assault;
    class My_DF_Gear_Rigs_BlackHawk;
    class My_DF_Gear_Rigs_Butterfly;
    class My_DF_Gear_Rigs_Claire;
    class My_DF_Gear_Rigs_D01;
    class My_DF_Gear_Rigs_DAR;
    class My_DF_Gear_Rigs_Dash;
    class My_DF_Gear_Rigs_Dash_Camo;
    class My_DF_Gear_Rigs_Dash_Camo2;
    class My_DF_Gear_Rigs_DRC;
    class My_DF_Gear_Rigs_DSA;
    class My_DF_Gear_Rigs_Exoskeleton;
    class My_DF_Gear_Rigs_Exoskeleton_Camo;
    class My_DF_Gear_Rigs_Exoskeleton_SXI253M;
    class My_DF_Gear_Rigs_Exoskeleton_Pro;
    class My_DF_Gear_Rigs_G01;
    class My_DF_Gear_Rigs_GIR;
    class My_DF_Gear_Rigs_Hack;
    class My_DF_Gear_Rigs_Hack_Haavk;
    class My_DF_Gear_Rigs_Hack_ink;
    class My_DF_Gear_Rigs_HD3;
    class My_DF_Gear_Rigs_Heavy_Armor;
    class My_DF_Gear_Rigs_Heavy_Armor_Black;
    class My_DF_Gear_Rigs_HK3;
    class My_DF_Gear_Rigs_Hurricane;
    class My_DF_Gear_Rigs_JetSystem_Outers;
    class My_DF_Gear_Rigs_Landon;
    class My_DF_Gear_Rigs_Lightweight;
    class My_DF_Gear_Rigs_Luna_Black;
    class My_DF_Gear_Rigs_Luna;
    class My_DF_Gear_Rigs_Maurice;
    class My_DF_Gear_Rigs_Mounting;
    class My_DF_Gear_Rigs_Nylon;
    class My_DF_Gear_Rigs_OperationDragon;
    class My_DF_Gear_Rigs_Pilot;
    class My_DF_Gear_Rigs_Pocket;
    class My_DF_Gear_Rigs_Raider;
    class My_DF_Gear_Rigs_Rapid;
    class My_DF_Gear_Rigs_Reis;
    class My_DF_Gear_Rigs_Rocketeer;
    class My_DF_Gear_Rigs_Simple;
    class My_DF_Gear_Rigs_Sineva;
    class My_DF_Gear_Rigs_Sineva_Haavk;
    class My_DF_Gear_Rigs_Universal;

    // Backpack durability: original baseline observed at 500 HP.
    #define EOH_DF_BACKPACK_DURABILITY(CLASSNAME) class CLASSNAME { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; }

    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_Shiled2);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_Large_Mountain);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_Camping);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_Cross);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_D2);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_D3);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_D7);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_DASH);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_DG);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_Doctor);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_Engineering_Shield_LV1);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_Engineering_Shield_LV2);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_Engineering_Shield_LV3);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_Engineering_Shield_LV4);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_Field_hiking);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_GA);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_GT1);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_GT5);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_GTO);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_Heavy_Mountain);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_HLS2);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_Kai);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_Kai_Haavk);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_King);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_Zoya_Angel);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_Large_sports);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_Lightweight_Outdoor);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_Lightweight_Outdoor2);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_MAP);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_Raid_Tactical);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_Rainforest_hunter);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_Rocket);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_Roy);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_Roy_Haavk);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_Roy_mourners);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_Rucksack);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_SergeantWilson);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_Shiled);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_Sineva_Tincan);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_Sports);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_Subrosa);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_Tactical);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_Terry);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_Terry_Haavk);
    EOH_DF_BACKPACK_DURABILITY(My_DF_Gear_Backpacks_Travel);

    // Headgear/rig durability: original baseline observed at 100 HP. Light Reis hat was 50 HP.
    #define EOH_DF_GEAR_DURABILITY(CLASSNAME) class CLASSNAME { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; transferToAttachmentsCoef = 0.35; }; }; }; }
    #define EOH_DF_ATTACHMENT_DURABILITY(CLASSNAME) class CLASSNAME { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; }; }; }; }

    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_GT5);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_Benny);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_Butterfly);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_D6);
    EOH_DF_ATTACHMENT_DURABILITY(My_DF_Gear_Heads_D6_Visor);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_DAS);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_David_Savage);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_DICH);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_DICH1);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_DICH9);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_Dragon);
    EOH_DF_ATTACHMENT_DURABILITY(My_DF_Gear_Heads_Dragon_NVG);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_Dragon_Outers);
    EOH_DF_ATTACHMENT_DURABILITY(My_DF_Gear_Heads_Dragon_Outers_NVG);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_DRO);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_Elio);
    EOH_DF_ATTACHMENT_DURABILITY(My_DF_Gear_Heads_Elio_NVG);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_Eversmann);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_Flamethrower);
    EOH_DF_ATTACHMENT_DURABILITY(My_DF_Gear_Heads_Flamethrower_Visor);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_FPilot);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_GN);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_GN_Heavy);
    EOH_DF_ATTACHMENT_DURABILITY(My_DF_Gear_Heads_GN_Heavy_NVG);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_GT1);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_Guard);
    EOH_DF_ATTACHMENT_DURABILITY(My_DF_Gear_Heads_Guard_NVG);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_H01);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_H07);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_H09);
    EOH_DF_ATTACHMENT_DURABILITY(My_DF_Gear_Heads_H09_Visor);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_H70);
    EOH_DF_ATTACHMENT_DURABILITY(My_DF_Gear_Heads_H70_NVG);
    class My_DF_Gear_Hat_Reis { class DamageSystem { class GlobalHealth { class Health { hitpoints = 100; }; }; }; };
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_Headphone);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_Headphone2);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_Headphone3);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_Heavy_Armor);
    EOH_DF_ATTACHMENT_DURABILITY(My_DF_Gear_Heads_Heavy_Armor_Visor);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_Heavy_Armor2);
    EOH_DF_ATTACHMENT_DURABILITY(My_DF_Gear_Heads_Heavy_Armor2_Visor);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_Heavy);
    EOH_DF_ATTACHMENT_DURABILITY(My_DF_Gear_Heads_Heavy_Visor);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_Hoot);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_Kai);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_Long);
    EOH_DF_ATTACHMENT_DURABILITY(My_DF_Gear_Heads_Long_NVG);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_Luna_Black);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_Luna_Olymp);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_Mask);
    EOH_DF_ATTACHMENT_DURABILITY(My_DF_Gear_Heads_Mask_Visor);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_MC);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_MC201);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_MHS);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_Mythic);
    EOH_DF_ATTACHMENT_DURABILITY(My_DF_Gear_Heads_Mythic_NVG);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_Nightsuit);
    EOH_DF_ATTACHMENT_DURABILITY(My_DF_Gear_Heads_Nightsuit_NVG);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_Old);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_OperationDragon);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_Outdoor);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_Pilot);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_Riot);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_Safety);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_Said);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_Scout);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_SergeantWilson);
    EOH_DF_ATTACHMENT_DURABILITY(My_DF_Gear_Heads_SergeantWilson_NVG);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_Sineva);
    EOH_DF_ATTACHMENT_DURABILITY(My_DF_Gear_Heads_Sineva_Visor);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_Sineva_Tincan);
    EOH_DF_ATTACHMENT_DURABILITY(My_DF_Gear_Heads_Sineva_Tincan_Visor);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Heads_Vintage);

    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_Assault);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_BlackHawk);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_Butterfly);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_Claire);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_D01);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_DAR);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_Dash);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_Dash_Camo);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_Dash_Camo2);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_DRC);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_DSA);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_Exoskeleton);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_Exoskeleton_Camo);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_Exoskeleton_SXI253M);
    EOH_DF_ATTACHMENT_DURABILITY(My_DF_Gear_Rigs_Exoskeleton_Pro);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_G01);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_GIR);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_Hack);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_Hack_Haavk);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_Hack_ink);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_HD3);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_Heavy_Armor);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_Heavy_Armor_Black);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_HK3);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_Hurricane);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_JetSystem_Outers);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_Landon);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_Lightweight);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_Luna_Black);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_Luna);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_Maurice);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_Mounting);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_Nylon);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_OperationDragon);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_Pilot);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_Pocket);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_Raider);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_Rapid);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_Reis);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_Rocketeer);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_Simple);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_Sineva);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_Sineva_Haavk);
    EOH_DF_GEAR_DURABILITY(My_DF_Gear_Rigs_Universal);
};
