class CfgPatches
{
    class EoH_DeltaForceDurability
    {
        units[] = {};
        weapons[] = {};
        requiredVersion = 0.1;
        requiredAddons[] =
        {
            "DZ_Data",
            "DZ_Characters",
            "DZ_Characters_Backpacks",
            "DZ_Characters_Headgear",
            "DZ_Characters_Glasses",
            "My_DF_Gear_Scripts"
        };
    };
};

class CfgVehicles
{
    class My_DF_Gear_Backpacks_Shiled2;
    class My_DF_Gear_Backpacks_Large_Mountain;
    class My_DF_Gear_Backpacks_Camping;
    class My_DF_Gear_Backpacks_Cross;
    class My_DF_Gear_Backpacks_D2;
    class My_DF_Gear_Backpacks_D3;
    class My_DF_Gear_Backpacks_D7;
    class My_DF_Gear_Backpacks_DASH;
    class My_DF_Gear_Backpacks_DG;
    class My_DF_Gear_Backpacks_Doctor;
    class My_DF_Gear_Backpacks_Engineering_Shield_LV1;
    class My_DF_Gear_Backpacks_Engineering_Shield_LV2;
    class My_DF_Gear_Backpacks_Engineering_Shield_LV3;
    class My_DF_Gear_Backpacks_Engineering_Shield_LV4;
    class My_DF_Gear_Backpacks_Field_hiking;
    class My_DF_Gear_Backpacks_GA;
    class My_DF_Gear_Backpacks_GT1;
    class My_DF_Gear_Backpacks_GT5;
    class My_DF_Gear_Backpacks_GTO;
    class My_DF_Gear_Backpacks_Heavy_Mountain;
    class My_DF_Gear_Backpacks_HLS2;
    class My_DF_Gear_Backpacks_Kai;
    class My_DF_Gear_Backpacks_Kai_Haavk;
    class My_DF_Gear_Backpacks_King;
    class My_DF_Gear_Backpacks_Zoya_Angel;
    class My_DF_Gear_Backpacks_Large_sports;
    class My_DF_Gear_Backpacks_Lightweight_Outdoor;
    class My_DF_Gear_Backpacks_Lightweight_Outdoor2;
    class My_DF_Gear_Backpacks_MAP;
    class My_DF_Gear_Backpacks_Raid_Tactical;
    class My_DF_Gear_Backpacks_Rainforest_hunter;
    class My_DF_Gear_Backpacks_Rocket;
    class My_DF_Gear_Backpacks_Roy;
    class My_DF_Gear_Backpacks_Roy_Haavk;
    class My_DF_Gear_Backpacks_Roy_mourners;
    class My_DF_Gear_Backpacks_Rucksack;
    class My_DF_Gear_Backpacks_SergeantWilson;
    class My_DF_Gear_Backpacks_Shiled;
    class My_DF_Gear_Backpacks_Sineva_Tincan;
    class My_DF_Gear_Backpacks_Sports;
    class My_DF_Gear_Backpacks_Subrosa;
    class My_DF_Gear_Backpacks_Tactical;
    class My_DF_Gear_Backpacks_Terry;
    class My_DF_Gear_Backpacks_Terry_Haavk;
    class My_DF_Gear_Backpacks_Travel;

    class My_DF_Gear_Heads_GT5;
    class My_DF_Gear_Heads_Benny;
    class My_DF_Gear_Heads_Butterfly;
    class My_DF_Gear_Heads_D6;
    class My_DF_Gear_Heads_D6_Visor;
    class My_DF_Gear_Heads_DAS;
    class My_DF_Gear_Heads_David_Savage;
    class My_DF_Gear_Heads_DICH;
    class My_DF_Gear_Heads_DICH1;
    class My_DF_Gear_Heads_DICH9;
    class My_DF_Gear_Heads_Dragon;
    class My_DF_Gear_Heads_Dragon_NVG;
    class My_DF_Gear_Heads_Dragon_Outers;
    class My_DF_Gear_Heads_Dragon_Outers_NVG;
    class My_DF_Gear_Heads_DRO;
    class My_DF_Gear_Heads_Elio;
    class My_DF_Gear_Heads_Elio_NVG;
    class My_DF_Gear_Heads_Eversmann;
    class My_DF_Gear_Heads_Flamethrower;
    class My_DF_Gear_Heads_Flamethrower_Visor;
    class My_DF_Gear_Heads_FPilot;
    class My_DF_Gear_Heads_GN;
    class My_DF_Gear_Heads_GN_Heavy;
    class My_DF_Gear_Heads_GN_Heavy_NVG;
    class My_DF_Gear_Heads_GT1;
    class My_DF_Gear_Heads_Guard;
    class My_DF_Gear_Heads_Guard_NVG;
    class My_DF_Gear_Heads_H01;
    class My_DF_Gear_Heads_H07;
    class My_DF_Gear_Heads_H09;
    class My_DF_Gear_Heads_H09_Visor;
    class My_DF_Gear_Heads_H70;
    class My_DF_Gear_Heads_H70_NVG;
    class My_DF_Gear_Hat_Reis;
    class My_DF_Gear_Heads_Headphone;
    class My_DF_Gear_Heads_Headphone2;
    class My_DF_Gear_Heads_Headphone3;
    class My_DF_Gear_Heads_Heavy_Armor;
    class My_DF_Gear_Heads_Heavy_Armor_Visor;
    class My_DF_Gear_Heads_Heavy_Armor2;
    class My_DF_Gear_Heads_Heavy_Armor2_Visor;
    class My_DF_Gear_Heads_Heavy;
    class My_DF_Gear_Heads_Heavy_Visor;
    class My_DF_Gear_Heads_Hoot;
    class My_DF_Gear_Heads_Kai;
    class My_DF_Gear_Heads_Long;
    class My_DF_Gear_Heads_Long_NVG;
    class My_DF_Gear_Heads_Luna_Black;
    class My_DF_Gear_Heads_Luna_Olymp;
    class My_DF_Gear_Heads_Mask;
    class My_DF_Gear_Heads_Mask_Visor;
    class My_DF_Gear_Heads_MC;
    class My_DF_Gear_Heads_MC201;

    class My_DF_Gear_Backpacks_Shiled2 { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_Large_Mountain { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_Camping { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_Cross { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_D2 { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_D3 { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_D7 { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_DASH { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_DG { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_Doctor { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_Engineering_Shield_LV1 { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_Engineering_Shield_LV2 { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_Engineering_Shield_LV3 { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_Engineering_Shield_LV4 { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_Field_hiking { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_GA { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_GT1 { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_GT5 { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_GTO { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_Heavy_Mountain { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_HLS2 { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_Kai { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_Kai_Haavk { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_King { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_Zoya_Angel { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_Large_sports { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_Lightweight_Outdoor { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_Lightweight_Outdoor2 { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_MAP { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_Raid_Tactical { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_Rainforest_hunter { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_Rocket { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_Roy { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_Roy_Haavk { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_Roy_mourners { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_Rucksack { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_SergeantWilson { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_Shiled { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_Sineva_Tincan { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_Sports { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_Subrosa { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_Tactical { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_Terry { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_Terry_Haavk { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Backpacks_Travel { class DamageSystem { class GlobalHealth { class Health { hitpoints = 875; transferToAttachmentsCoef = 0.35; }; }; }; };

    class My_DF_Gear_Heads_GT5 { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Heads_Benny { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Heads_Butterfly { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Heads_D6 { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Heads_D6_Visor { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; }; }; }; };
    class My_DF_Gear_Heads_DAS { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Heads_David_Savage { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Heads_DICH { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Heads_DICH1 { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Heads_DICH9 { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Heads_Dragon { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Heads_Dragon_NVG { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; }; }; }; };
    class My_DF_Gear_Heads_Dragon_Outers { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Heads_Dragon_Outers_NVG { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; }; }; }; };
    class My_DF_Gear_Heads_DRO { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Heads_Elio { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Heads_Elio_NVG { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; }; }; }; };
    class My_DF_Gear_Heads_Eversmann { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Heads_Flamethrower { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Heads_Flamethrower_Visor { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; }; }; }; };
    class My_DF_Gear_Heads_FPilot { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Heads_GN { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Heads_GN_Heavy { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Heads_GN_Heavy_NVG { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; }; }; }; };
    class My_DF_Gear_Heads_GT1 { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Heads_Guard { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Heads_Guard_NVG { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; }; }; }; };
    class My_DF_Gear_Heads_H01 { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Heads_H07 { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Heads_H09 { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Heads_H09_Visor { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; }; }; }; };
    class My_DF_Gear_Heads_H70 { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Heads_H70_NVG { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; }; }; }; };
    class My_DF_Gear_Hat_Reis { class DamageSystem { class GlobalHealth { class Health { hitpoints = 100; }; }; }; };
    class My_DF_Gear_Heads_Headphone { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Heads_Headphone2 { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Heads_Headphone3 { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Heads_Heavy_Armor { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Heads_Heavy_Armor_Visor { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; }; }; }; };
    class My_DF_Gear_Heads_Heavy_Armor2 { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Heads_Heavy_Armor2_Visor { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; }; }; }; };
    class My_DF_Gear_Heads_Heavy { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Heads_Heavy_Visor { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; }; }; }; };
    class My_DF_Gear_Heads_Hoot { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Heads_Kai { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Heads_Long { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Heads_Long_NVG { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; }; }; }; };
    class My_DF_Gear_Heads_Luna_Black { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Heads_Luna_Olymp { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Heads_Mask { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Heads_Mask_Visor { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; }; }; }; };
    class My_DF_Gear_Heads_MC { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; transferToAttachmentsCoef = 0.35; }; }; }; };
    class My_DF_Gear_Heads_MC201 { class DamageSystem { class GlobalHealth { class Health { hitpoints = 200; transferToAttachmentsCoef = 0.35; }; }; }; };
};
